### ISSUE TITLE
How long can Support Support <For /> tag

### ISSUE THREAD

**Issue by Zian502** [intpp/swc-plugin-jsx-control-statements#3]
Please take the time to support the boss

**Comment by Zian502** [comment]
https://github.com/intpp/swc-plugin-jsx-control-statements/pull/7

**Comment by intpp** [comment]
Published in [v0.6.0](https://github.com/intpp/swc-plugin-jsx-control-statements/releases/tag/0.6.0)

Thanks for contribution!
