### ISSUE TITLE
Can swc core be upgraded to 0.89.x

### ISSUE THREAD

**Issue by Zian502** [intpp/swc-plugin-jsx-control-statements#5]
![image](https://github.com/intpp/swc-plugin-jsx-control-statements/assets/26033663/d603886d-ba65-4ce1-bf99-e080bcbf58e3)

**Comment by intpp** [comment]
Hi. Yes, I will update

**Comment by intpp** [comment]
https://github.com/intpp/swc-plugin-jsx-control-statements/releases/tag/0.3.0
